## 01-01 Tensor Introduction

In [2]:
import numpy as np
import torch

torch.manual_seed(0)
torch.__version__

'1.3.0'

通过`torch.tensor`创建向量

In [26]:
test_array = np.ones((3, 3))
print('test_array数据类型：', test_array.dtype)

test_tensor = torch.tensor(test_array, device='cuda')
print('test_tensor数据：\n', test_tensor)

test_array数据类型： float64
test_tensor数据：
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', dtype=torch.float64)


通过`torch.from_numpy`创建张量

In [19]:
test_array = np.array([[1, 2, 3], [4, 5, 6]])
test_tensor = torch.from_numpy(test_array)
print('原始数据')
print('test_array数据：\n', test_array)
print('test_tensor数据：\n', test_tensor)

test_array[0, 0] = 0
print('\n修改test_array后')
print('test_array数据：\n', test_array)
print('test_tensor数据：\n', test_tensor)

test_tensor[0, 0] = -1
print('\n修改test_tensor后')
print('test_array数据：\n', test_array)
print('test_tensor数据：\n', test_tensor)

原始数据
test_array数据：
 [[1 2 3]
 [4 5 6]]
test_tensor数据：
 tensor([[1, 2, 3],
        [4, 5, 6]])

修改test_array后
test_array数据：
 [[0 2 3]
 [4 5 6]]
test_tensor数据：
 tensor([[0, 2, 3],
        [4, 5, 6]])

修改test_tensor后
test_array数据：
 [[-1  2  3]
 [ 4  5  6]]
test_tensor数据：
 tensor([[-1,  2,  3],
        [ 4,  5,  6]])


通过`torch.zeros`创建张量

In [23]:
out_tensor = torch.tensor([1])
test_tensor = torch.zeros((3, 3), out=out_tensor)
print('比较这两个tensor的数据和id')
print(out_tensor, '\n', test_tensor)
print(id(out_tensor), id(test_tensor), id(out_tensor) == id(test_tensor))

比较这两个tensor的数据和id
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
139789211445920 139789211445920 True


通过`torch.full`创建张量

In [24]:
test_tensor = torch.full((3, 3), 2)
print('test_tensor数据：\n', test_tensor)

test_tensor数据：
 tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


通过`torch.arange`创建等差数列张量

In [25]:
test_tensor  = torch.arange(2, 10, 2)
print('test_tensor数据：\n', test_tensor)

test_tensor数据：
 tensor([2, 4, 6, 8])


通过`torch.linspace`创建均分数列张量

In [27]:
test_tensor = torch.linspace(2, 10, 5)
print('test_tensor数据：\n', test_tensor)

test_tensor数据：
 tensor([ 2.,  4.,  6.,  8., 10.])


通过`torch.normal`创建正态分布张量

In [31]:
mean_tensor = torch.arange(1, 5, dtype=torch.float)
std_tensor = torch.arange(1, 5, dtype=torch.float)
test_tensor = torch.normal(mean_tensor, std_tensor)
print('mean_tensor数据：\n', mean_tensor)
print('std_tensor数据：\n', std_tensor)
print('test_tensor数据：\n', test_tensor)
print()

test_tensor = torch.normal(0., 1., size=(4,))
print('test_tensor数据：\n', test_tensor)
print()

test_tensor = torch.normal(mean=mean_tensor, std=1.)
print('test_tensor数据：\n', test_tensor)

mean_tensor数据：
 tensor([1., 2., 3., 4.])
std_tensor数据：
 tensor([1., 2., 3., 4.])
test_tensor数据：
 tensor([1.3704, 4.9130, 5.8194, 7.0994])

test_tensor数据：
 tensor([ 0.1919,  1.2638, -1.2904, -0.7911])

test_tensor数据：
 tensor([0.9791, 1.2815, 3.5186, 2.6875])
