## 01-04 Computation Graph

In [7]:
import torch

torch.__version__

'1.3.0'

分析下述式子的计算图  `y=(w+x)(w+1)`

In [8]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)

a = torch.add(w, x)
a.retain_grad()  # 保存非叶子节点的梯度
b = torch.add(w, 1)
y = torch.mul(a, b)

print(y)

tensor([6.], grad_fn=<MulBackward0>)


反向传播计算梯度

In [9]:
y.backward()
print(w.grad)

tensor([5.])


查看叶子节点

In [10]:
print(w.is_leaf, x.is_leaf, a.is_leaf, b.is_leaf, y.is_leaf)

True True False False False


查看梯度

In [11]:
print(w.grad, x.grad, a.grad, b.grad, y.grad)

tensor([5.]) tensor([2.]) tensor([2.]) None None


查看`grad_fn`

In [12]:
print(w.grad_fn, x.grad_fn, a.grad_fn, b.grad_fn, y.grad_fn)

None None <AddBackward0 object at 0x7f09e703d290> <AddBackward0 object at 0x7f09e703db90> <MulBackward0 object at 0x7f09e703dc10>
